--CREATE TABLE users (
--    customerID INT AUTO_INCREMENT PRIMARY KEY,
--    firstName VARCHAR(50) NOT NULL,
--    lastName VARCHAR(50) NOT NULL,
--    email VARCHAR(100) NOT NULL UNIQUE,
--    isAdmin BOOLEAN NOT NULL DEFAULT FALSE
--);

ALTER TABLE Users ADD COLUMN password VARCHAR(255) NOT NULL;



